//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CardSearcher.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardSearcher.Resources.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string LabelHide
        {
            get
            {
                return ResourceManager.GetString("LabelHide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string LabelLock
        {
            get
            {
                return ResourceManager.GetString("LabelLock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string LabelOpacity
        {
            get
            {
                return ResourceManager.GetString("LabelOpacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string LabelScale
        {
            get
            {
                return ResourceManager.GetString("LabelScale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LabelSettings
        {
            get
            {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string LabelShow
        {
            get
            {
                return ResourceManager.GetString("LabelShow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string LabelUnlock
        {
            get
            {
                return ResourceManager.GetString("LabelUnlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A Plugin Template.
        /// </summary>
        internal static string TextDescription
        {
            get
            {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MyPluginTemplate.
        /// </summary>
        internal static string TextName
        {
            get
            {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
    }
}
